services:
  nms-dashboard:
    build: .
    container_name: nms-dashboard
    restart: always
    env_file:
      - .env
    environment:
      - TZ=Asia/Jakarta
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./:/app
